name: Plug project CICD


on:
  push:
    branches: [ "master" ]
#------------------------------------------------
env:
  PROJECT_NAME: team11-tabling
  BUCKET_NAME: team11-tabling-bucket2
  CODE_DEPLOY_APP_NAME: tabling-codedeploy
  DEPLOYMENT_GROUP_NAME: tabling-codedeploy-group
#------------------------------------------------


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Set up application.properties
        run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
        shell: bash

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


#      - name:  application.properties 파일 만들기
#        run: |
#          cd ./src/main/resources
#          touch ./application.properties
#          echo "${{ secrets.PROPERTIES }}" > ./application.properties
#        shell: bash

      - name: Gradle 파일 생성
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5




      - name: gradlew 권한 부여, 빌드
        run:  |
          chmod +x ./gradlew
          ./gradlew bootJar

      #------------------------------------------------

      - name: ZIP 파일 생성
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment
          --application-name $CODE_DEPLOY_APP_NAME
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name $DEPLOYMENT_GROUP_NAME
          --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip

